M48
; DRILL file {KiCad (6.0.7)} date Sun Aug 28 16:54:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-28T16:54:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X4.5934Y-2.4511
X4.5934Y-4.3802
X6.8768Y-2.4511
X6.8768Y-4.3802
T0
M30
